### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by glouppe** [MechCoder/scikit-optimize#1]
If we plan on getting serious with this, we should think of a better project name. 

One that I like would be `scikit-optimize`, abbreviated as `skopt`. 

CC: @MechCoder @betatim

**Comment by betatim** [comment]
:+1:

Sounds like a good name and I am not particularly creative today for some punny name.

**Comment by MechCoder** [comment]
I am okay with `scikit-optimize`. What are your thoughts on creating a private organization for now? (as asked in the email)

**Comment by betatim** [comment]
I'm not a fan of private orgs/repos, so I would say: convince me ;) This is a open-source effort after all.

**Comment by MechCoder** [comment]
OK. Should we rename? But I think that something in the name should suggest that this is different from the conventional optimization procedures.

**Comment by MechCoder** [comment]
I'll take that back. Let us not discuss too much about this and rename it as skopt for now

**Comment by glouppe** [comment]
+1, let us not overthink too much yet :)

**Comment by betatim** [comment]
:ship: it

**Comment by MechCoder** [comment]
I have rechristened her scikit-optimize :-)
