### ISSUE TITLE
GBRT based minimization

### ISSUE THREAD

**Issue by MechCoder** [MechCoder/scikit-optimize#24]
GBRT now returns the quantiles. We can get a naive approximation to the std by subtracting the 68th quantile from the 50th quantile and feeding it to the acquistion functions.

**Comment by MechCoder** [comment]
@betatim

**Comment by betatim** [comment]
I will work on this.

**Comment by MechCoder** [comment]
Just curious, are there methods that use GBRT's already? If not is it possible we could publish something?
