### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by betatim** [MechCoder/scikit-optimize#27]
This repo needs a license. BSD tres clauses?

The other kind of [three comma club](http://49.media.tumblr.com/fb1074d69e2c82f7671c39bfa49f38c5/tumblr_no1lzcGMFW1trb5guo1_400.gif)

**Comment by glouppe** [comment]
+1 for bsd

**Comment by glouppe** [comment]
Mentions of the license should also be added to all files.

**Comment by betatim** [comment]
A header like this:

```python
"""Describe the file."""

# Author: Joey Bloggy <joey.bloggy@example.com>
# License: BSD 3 clause
```

or instead of mentioning individual authors should it just say `The scikit-optimize team` or something? IANAL :confused:

**Comment by glouppe** [comment]
I prefer mentioning individual authors. This is often very useful a few years after (often when debugging) to get back in touch with the original authors.

**Comment by MechCoder** [comment]
Sounds ok, feel free to send a PR

**Comment by MechCoder** [comment]
See: https://github.com/MechCoder/scikit-optimize/pull/33
