### ISSUE TITLE
Explicit is better than implicit

### ISSUE THREAD

**Issue by betatim** [MechCoder/scikit-optimize#3]
This sounds like a incredibly formal, bureaucratic and heavy, try and read to the end before panicking.

I think one of the first things we should do is make sure we are all on the same page on how the project will work. I suggest the following:

* all changes by PR
* a PR solves one problem (don't mix problems together in one PR) with the minimal set of changes
* describe why you are proposing the changes you are proposing
* try to not rush changes (definition of rush depends on how big your changes are)
* someone else has to merge your PR
* new code needs to come with a test
* no merging if travis is red

I don't see this as rules to be enforced by :police_car: but as guidelines.

I think it is important to write down briefly these kind of "obvious" things if you want to start a project that is long term (not just a hackathon hack) with people who you haven't worked with so much. Basically: explicit is better than implicit :grinning:

**Comment by betatim** [comment]
I forgot: no legacy python right? :trollface:

**Comment by MechCoder** [comment]
Great, I promise to abide by these guidelines now since I've just set everything up.

**Comment by glouppe** [comment]
Could you put all this within a `CONTRIBUTING.rst` file? As an issue, it will eventually get lost :)

**Comment by glouppe** [comment]
Fixed in #7
