### ISSUE TITLE
How does the parameters being of different scales affect the Gaussian Process?

### ISSUE THREAD

**Issue by MechCoder** [MechCoder/scikit-optimize#48]
The reason I scaled all the parameters to between 0 and 1 to make the GP fitting invariant of the scale of parameters.

I am sure that using an anisotropic kernel as being done now makes it invariant of the different scales of the paramters but it might be worth investigating.

**Comment by betatim** [comment]
Is there a good benchmark problem that has very different scales for each parameter? Would it be enough to do a 2D parabola with minimum at (1,1000)?
