### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by MechCoder** [MechCoder/scikit-optimize#8]
The current three tests take 17 mins to run on Travis, while the entire sklearn test suite runs in 10 mins

**Comment by betatim** [comment]
[Link to a CI log](https://travis-ci.org/MechCoder/scikit-optimize/jobs/117981589)

200seconds to install `conda`, do we really need a conda env?

The bulk of the time is spent in actual tests, can we simplify them and test small parts instead of full blown optimisations??

**Comment by glouppe** [comment]
The easiest solution is simply to reduce `maxiter`. We can show that it works in much fewer iterations.

**Comment by MechCoder** [comment]
I don't really understand how but I brought it down to 6 minutes with this commit. https://github.com/MechCoder/scikit-optimize/commit/395f9dd40807cd0e17fae543420fa7b042a88e3f

**Comment by glouppe** [comment]
What also takes some time is compiling scikit-learn master. Hopefully, this will be solved after the next release. In #12, tests are now down to 5mn total.

**Comment by glouppe** [comment]
Closing this, tests are now fine.
